// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWr9GG1OMoLp7U6i0MzpMh1mufkvJtrC4',
    appId: '1:82126294539:web:9afe8a7c31029125ef410e',
    messagingSenderId: '82126294539',
    projectId: 'todo-list-flutter-82',
    authDomain: 'todo-list-flutter-82.firebaseapp.com',
    storageBucket: 'todo-list-flutter-82.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4If3aBJCzXZTSG00ufdKGVc7dlTurxNA',
    appId: '1:82126294539:android:b1efb57e56e1b54bef410e',
    messagingSenderId: '82126294539',
    projectId: 'todo-list-flutter-82',
    storageBucket: 'todo-list-flutter-82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9-7HRoeZtq9DMBV59Nd5MxBejQxHVd_g',
    appId: '1:82126294539:ios:95de65fde285dc7aef410e',
    messagingSenderId: '82126294539',
    projectId: 'todo-list-flutter-82',
    storageBucket: 'todo-list-flutter-82.appspot.com',
    iosClientId: '82126294539-cpn999kjc4hkehilc8co8a8v857hej46.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTodoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9-7HRoeZtq9DMBV59Nd5MxBejQxHVd_g',
    appId: '1:82126294539:ios:95de65fde285dc7aef410e',
    messagingSenderId: '82126294539',
    projectId: 'todo-list-flutter-82',
    storageBucket: 'todo-list-flutter-82.appspot.com',
    iosClientId: '82126294539-cpn999kjc4hkehilc8co8a8v857hej46.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTodoApp',
  );
}
